apiVersion: v1
entries:
  apollo-portal:
  - apiVersion: v2
    appVersion: 1.7.0-SNAPSHOT
    created: "2020-07-26T15:24:49.445615+08:00"
    description: A Helm chart for Apollo Portal
    digest: 913e52516c537f5dac72949850b15026cddcd33a38d463d52cb73edba3f9a033
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-portal
    type: application
    urls:
    - apollo-portal-0.1.0.tgz
    version: 0.1.0
  apollo-service:
  - apiVersion: v2
    appVersion: 1.7.0-SNAPSHOT
    created: "2020-07-26T15:24:49.447484+08:00"
    description: A Helm chart for Apollo Config Service and Apollo Admin Service
    digest: 7b1fbebb99b9e31153fb8ca7d5a6acae53b29635a34a01ae405ffcd7c60ed771
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-service
    type: application
    urls:
    - apollo-service-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-26T15:24:49.440259+08:00"
