apiVersion: v1
entries:
  apollo-portal:
  - apiVersion: v2
    appVersion: 1.7.0-SNAPSHOT
    created: "2020-06-14T21:34:11.399747+08:00"
    description: A Helm chart for Apollo Portal
    digest: 927c354d7b955c0900376edfc63c831c5b4b63ac3a78629462da36bc931d0d93
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-portal
    type: application
    urls:
    - apollo-portal-0.1.0.tgz
    version: 0.1.0
  apollo-service:
  - apiVersion: v2
    appVersion: 1.7.0-SNAPSHOT
    created: "2020-06-14T21:34:11.40067+08:00"
    description: A Helm chart for Apollo Config Service and Apollo Admin Service
    digest: 711201ff381a9d7eacc9c8a6fb106a2fb69be3358f08f395f2c42a1604f33eda
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-service
    type: application
    urls:
    - apollo-service-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-14T21:34:11.398248+08:00"
