apiVersion: v1
entries:
  apollo-portal:
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2020-08-01T20:26:39.623023+08:00"
    description: A Helm chart for Apollo Portal
    digest: b838e4478f0c031093691defeffb5805d51189989db0eb9caaa2dc67905c8391
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-portal
    type: application
    urls:
    - apollo-portal-0.1.0.tgz
    version: 0.1.0
  apollo-service:
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2020-08-01T20:26:39.623669+08:00"
    description: A Helm chart for Apollo Config Service and Apollo Admin Service
    digest: 65c08f39b54ad1ac1d849cc841ce978bd6e95b0b6cbd2423d9f17f66bc7e8d3e
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-service
    type: application
    urls:
    - apollo-service-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-01T20:26:39.621531+08:00"
